### ISSUE TITLE
I can change by code, pins SPI and SS? 

### ISSUE THREAD

**Issue by domonetic** [ntruchsess/arduino_uip#117]
I can change by code, the SS pin? I have a connecting plate otherwise the A0 pin.

**Comment by rodjt** [comment]
SS is defined in library file Enc28J60Network.h.
#define ENC28J60_CONTROL_CS  SS
make SS your board select pin#.

Be aware that the default SS pin is still required by the hardware if you are using the SPI bus even if you have changed the ENC28J60 SS to another pin. You may be able to completely shut down the SPI and reconfigure the pins if you want to use the SS pin for something else. Then re-initialize the SPI for next use, but I have not tried this.

**Comment by domonetic** [comment]
Ok thanks
