### ISSUE TITLE
error in aton from Dns.cpp

### ISSUE THREAD

**Issue by nottledim** [ntruchsess/arduino_uip#130]
If you're looking for dots and numbers then the test in aton() is better written:

 ( (*p == '.') || ((*p >= '0') && (*p <= '9')) )) rather than

 ( (*p == '.') || (*p >= '0') || (*p <= '9') ))

See Dns.h line 62

**Comment by ntruchsess** [comment]
good point. Fixed -> https://github.com/ntruchsess/arduino_uip/commit/aae9008dfdab7e61b2e2573b99017e292a1ab480
