### ISSUE TITLE
Add function getRemoteIP()

### ISSUE THREAD

**Issue by FernandoGarcia** [ntruchsess/arduino_uip#68]
Hi!

Please, you can tell me how add this function to your library?

EthernetClient.cpp

uint8_t *EthernetClient::getRemoteIP(uint8_t remoteIP[])
{
  W5100.readSnDIPR(_sock, remoteIP);
  return remoteIP;
}

EthernetClient.h

uint8_t *getRemoteIP(uint8_t RemoteIP[]);

I found it to ethernet.h but  I don't know what use to "W5100.readSnDIPR" in your library.

Best regards.

**Comment by myrzeug** [comment]
Hi, 

Maybe it's too late already, but it may serve in the future to others like me
I added the functionality adding these lines in the library, may not be the best way but it works for me

in UIPClient.h add this line in class UIPClient  just before  "private:"
 >IPAddress  myremoteIP();

in UIPClient.pp At the end of file for example

> IPAddress
UIPClient::remoteIP() {  
  if (data)
  {  
    return ip_addr_uip(uip_conns[data->state & UIP_CLIENT_SOCKETS].ripaddr);   
  }    
  return  IPAddress();       
}




(The Ext version for me does not work, I successfully raise the server, but at the second login from the browser the server is never active: UIPEthernet_v1.09_ext  in arduino Due)
The modifications I have made on the normal version "UIPEthernet_v1.59 - for Arduino 1.5.x"  and I use arduino Due
