### ISSUE TITLE
ENC28J60 stops reacting to network after TCP Retransmission packet

### ISSUE THREAD

**Issue by philfreeeu** [ntruchsess/arduino_uip#92]
Hello!

I am using UIPEthernet version 1.07. My arduino sketch implements gets DHCP address and runs one server. 
I have 4 clients, that are connecting to that server once per second, send a request, got and answer and disconnect. 
It works normally for a few minutes and then ENC28J60 stops to react to incoming TCP connections and also to ARP requests. Arduino code keeps working, it calls Ethernet.maintain(); once per minute and get's 0.

I've made a Wireshark dump of the communication and it looks that this behavour starts when ENC28J60 gets a TCP Retransmission packet. See this image:
![2014-10-07-152053_1280x1000_scrot](https://cloud.githubusercontent.com/assets/9050708/4541996/6ac3ed52-4e1c-11e4-8416-bfe7f98fc146.png)

It does not happen always, e.g. this retransmission happenned some time before and it did not hang:
![2014-10-07-153428_1280x1000_scrot](https://cloud.githubusercontent.com/assets/9050708/4542138/683419c0-4e1e-11e4-96a3-8d403f1991bf.png)

I have the complete Wireshark dump file for this session and can sent it or any other information you may require.

**Comment by JoaoPagotto** [comment]
![image](https://user-images.githubusercontent.com/18318284/53304122-b06d4100-3850-11e9-9081-6e996e135558.png)


Hello dear developers, after analyzing Wireshark I realized that UIPEthernet 2.0.7 and ENC28J60 is generating TCP Retransmissions, I am using it with an Arduino Nano. I open a connection with a TCP server and send and receive packets in a period of 20 packets per second, but with UIPEthernet happens from time to time also lose connection to the server, I have other hardware running in this same way PIC24FJ256GB106 and ENC28J60 with the Microchip TCPIP Stack v5.42.08 stack, and the Arduino Shield W5100, and these TCP Restransmissions problems do not occur. What could it be? If you can guide me in something so I can try to discover this bug in the library and be able to send it to you, any help is welcome. Thank you all.
